{% set name = "httplib2" %}
{% set version = "0.20.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/httplib2-{{ version }}.tar.gz
  sha256: 58a98e45b4b1a48273073f905d2961666ecf0fbac4250ea5b47aef259eb5c585

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - pytest
  run:
    - python >=3
    - pyparsing >=2.4.2,<4

test:
  imports:
    - httplib2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/httplib2/httplib2
  license: MIT
  license_file: LICENSE
  summary: A comprehensive HTTP client library

extra:
  recipe-maintainers:
    - ocefpaf
    - sigmavirus24
