{% set version = "0.11.3" %}

package:
  name: httplib2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/httplib2/httplib2-{{ version }}.tar.gz
  sha256: e71daed9a0e6373642db61166fa70beecc9bf04383477f84671348c02a04cbdf

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - httplib2

about:
  home: https://github.com/httplib2/httplib2
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A comprehensive HTTP client library'

extra:
  recipe-maintainers:
    - ocefpaf
    - sigmavirus24
