{% set version = "0.17.3" %}

package:
  name: httplib2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/httplib2/httplib2-{{ version }}.tar.gz
  sha256: 39dd15a333f67bfb70798faa9de8a6e99c819da6ad82b77f9a259a5c7b1225a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - httplib2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/httplib2/httplib2
  license: MIT
  license_file: LICENSE
  summary: A comprehensive HTTP client library

extra:
  recipe-maintainers:
    - ocefpaf
    - sigmavirus24
