{% set version = "0.11.0" %}

package:
  name: httplib2
  version: {{ version }}

source:
  fn: httplib2-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/httplib2/httplib2-{{ version }}.tar.gz
  sha256: 5c0138b53a2f13b1dc29707b75c04236e35247d6b5f2a14c930966e8f45ce3cc

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - httplib2

about:
  home: https://github.com/jcgregorio/httplib2
  license: MIT
  summary: 'A comprehensive HTTP client library'

extra:
  recipe-maintainers:
    - ocefpaf
    - sigmavirus24
