{% set version = "0.12.3" %}

package:
  name: httplib2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/httplib2/httplib2-{{ version }}.tar.gz
  sha256: a18121c7c72a56689efbf1aef990139ad940fee1e64c6f2458831736cd593600

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - httplib2

about:
  home: https://github.com/httplib2/httplib2
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A comprehensive HTTP client library'

extra:
  recipe-maintainers:
    - ocefpaf
    - sigmavirus24
