{% set version = "0.17.4" %}

package:
  name: httplib2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/httplib2/httplib2-{{ version }}.tar.gz
  sha256: 1e9340ecf0187a621bdcfb407c32e04e8e09fc6ab28b050efa38f20eae0e975f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - httplib2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/httplib2/httplib2
  license: MIT
  license_file: LICENSE
  summary: A comprehensive HTTP client library

extra:
  recipe-maintainers:
    - ocefpaf
    - sigmavirus24
