{% set name = "httplib2" %}
{% set version = "0.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/httplib2-{{ version }}.tar.gz
  sha256: ae39aed994e43f1001326b31eb904c2dca5b42c56c1569729041608ccc738a94

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - pytest
  run:
    - python >=3
    - pyparsing >=2.4.2,<3

test:
  imports:
    - httplib2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/httplib2/httplib2
  license: MIT
  license_file: LICENSE
  summary: A comprehensive HTTP client library

extra:
  recipe-maintainers:
    - ocefpaf
    - sigmavirus24
