# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "nrfdBVT1uGO6aKPIYlmsTi2Q/DRm1b5/hKWnBT1HqzOyMJOetuqI23T2p43WE/2UKUcPgFWVVDco1RO7x2J4pTvWUKaettHsFmPtJuwgEcJsiSI7QHFya7Ms2vMWlNJulESa4DA8VENE8FcVDnSesna6vJTfUHWZIfCOx7ThsB1WLbuUbgIxGVnVvlPZaG1x/xHbXkdRTTs+BK3Nns/CG1/+BvofPZfctzFElUESNEz2KlTg5BC7FFYG9+ufD+IX1/NuLWgAzp12kqU25ekubzWRdEflzkHqoBIQAg55c3ALCWp5T6nHFJo5WxqJEuts23PqHD3uQGXAsnbtPGCkZT+fNZDvUlOlLnesFxBX06hEITScwV0uTWZuOk7ST+PU3cX60DiZ8tN+nGiRJB8n4UD+SsfNqG1bAP3VuKq4JjPswF+EnbfWc0RB4JXTye1DLZsjRpJjVL1THEkKDZHhNr3xhvKgEv6og6SPfx74knuI3FZaoqKihNKAf2TIqH+z8Xwl4CsnM48v0q8lIX87FeOulspFIkpVxjFUi2hs85iFXuEfnBC7PR4V8M9yzMwEmu4Y7cMVPc3h7Altmu2y4N8/RHKXY6ZzM1hSohSrZ6l2p4+6m7/6G6KLN5dQlDtRxGvLDZ7BvGaiAPlig9gkA1X4NTCOefiTjE20iGMaebc="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
