# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "nrfdBVT1uGO6aKPIYlmsTi2Q/DRm1b5/hKWnBT1HqzOyMJOetuqI23T2p43WE/2UKUcPgFWVVDco1RO7x2J4pTvWUKaettHsFmPtJuwgEcJsiSI7QHFya7Ms2vMWlNJulESa4DA8VENE8FcVDnSesna6vJTfUHWZIfCOx7ThsB1WLbuUbgIxGVnVvlPZaG1x/xHbXkdRTTs+BK3Nns/CG1/+BvofPZfctzFElUESNEz2KlTg5BC7FFYG9+ufD+IX1/NuLWgAzp12kqU25ekubzWRdEflzkHqoBIQAg55c3ALCWp5T6nHFJo5WxqJEuts23PqHD3uQGXAsnbtPGCkZT+fNZDvUlOlLnesFxBX06hEITScwV0uTWZuOk7ST+PU3cX60DiZ8tN+nGiRJB8n4UD+SsfNqG1bAP3VuKq4JjPswF+EnbfWc0RB4JXTye1DLZsjRpJjVL1THEkKDZHhNr3xhvKgEv6og6SPfx74knuI3FZaoqKihNKAf2TIqH+z8Xwl4CsnM48v0q8lIX87FeOulspFIkpVxjFUi2hs85iFXuEfnBC7PR4V8M9yzMwEmu4Y7cMVPc3h7Altmu2y4N8/RHKXY6ZzM1hSohSrZ6l2p4+6m7/6G6KLN5dQlDtRxGvLDZ7BvGaiAPlig9gkA1X4NTCOefiTjE20iGMaebc="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
