travis:
  secure:
    BINSTAR_TOKEN: eiIJIwOFBoUj4taXdNnPNUIaU7sz/nCDxJMgDeKBGuBVA7m7ZNfgMdTS0D99zGa16NKrvP//9CAXpJH1qXyACL2/JCnuyhddxwtPFzus0YFXcIiI3HwjqWyb1NnFyRUvuAgHvNx5QQh8RAybpOFLXAxHa1Ex/S8BwN/50PQCzxdZA2G3JjKNeLCoitg6Tu5F+T+ar/5mGaN1SkdYRPJDsxaFMS4EsG35UCEKDiQTYh2ejWVhhvF49oun2TYU0I1N+KuYZJFsZgAE/YBWXFULMKcdwf/DAH8yqJyZ+KOB897kKrm13pJI60XK0xGSXdq0LPRPSuZIsdyOjMP8MQFHPq31NvbpQkMHbL8jTHyAl8RPaKKjnjc3PKKPrh8FcGz7Mx57s6L7DSLJL5UMKrWtwgkjcpeFVnt7p5hHcCYfZUMFZQg18QeZxVGBePRr21ToKNEJ68vN/cfvIi8/3YsOb5fz3GSJmsxIXb9hYvX/2rC1+ADYxb884HHN3QnxMfFiXQ9ZRUE7ikH2Ek47nr/2zRMfYuijNkWBW1WlYJo/L6jgTIYpA09xZ2W9zhTheA+T+K1ZXIZwprtPkf3ZvzuDqTwTiHzW712+k+O5J8Hyz1jNKOuMYmK0clC8WIUAZU+QLcmnQZIGA5B+3ekT9Z1F9UWNRBEwqHnq4yJEuRF527g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
