travis:
  secure:
    BINSTAR_TOKEN: nrfdBVT1uGO6aKPIYlmsTi2Q/DRm1b5/hKWnBT1HqzOyMJOetuqI23T2p43WE/2UKUcPgFWVVDco1RO7x2J4pTvWUKaettHsFmPtJuwgEcJsiSI7QHFya7Ms2vMWlNJulESa4DA8VENE8FcVDnSesna6vJTfUHWZIfCOx7ThsB1WLbuUbgIxGVnVvlPZaG1x/xHbXkdRTTs+BK3Nns/CG1/+BvofPZfctzFElUESNEz2KlTg5BC7FFYG9+ufD+IX1/NuLWgAzp12kqU25ekubzWRdEflzkHqoBIQAg55c3ALCWp5T6nHFJo5WxqJEuts23PqHD3uQGXAsnbtPGCkZT+fNZDvUlOlLnesFxBX06hEITScwV0uTWZuOk7ST+PU3cX60DiZ8tN+nGiRJB8n4UD+SsfNqG1bAP3VuKq4JjPswF+EnbfWc0RB4JXTye1DLZsjRpJjVL1THEkKDZHhNr3xhvKgEv6og6SPfx74knuI3FZaoqKihNKAf2TIqH+z8Xwl4CsnM48v0q8lIX87FeOulspFIkpVxjFUi2hs85iFXuEfnBC7PR4V8M9yzMwEmu4Y7cMVPc3h7Altmu2y4N8/RHKXY6ZzM1hSohSrZ6l2p4+6m7/6G6KLN5dQlDtRxGvLDZ7BvGaiAPlig9gkA1X4NTCOefiTjE20iGMaebc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
